# -*- coding: utf-8 -*-
"""MONTE CARLO SIMULATIO PROYECT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/151lR7yeT12vDrr8GBE1UN_3ebuIW2Ku8

# Monte Carlo Simulation ("Predict" PLTR Share Prices)

**REF**:https://youtu.be/fO-lGzZADVU
14 minute video that inspired this python project.

The word predict in this work will be in under "". Because I profoundly belief "predict" is a bs term. I prefer estimate. Also the documentation I have read reaches the consesus of predicting anything is ilogical. We can estimate a bulk of probable outcomes of random independents variables or events.


Tools like Monte Carlo simulations are used specifically when an analytical solution is impossible; they allow a researcher to estimate the fair value of a contract by simulating thousands of potential paths and taking the average result
. Similarly, Hidden Markov Models are used to estimate "latent" (unobservable) states of the market—like volatility regimes—by analyzing the patterns in observed data
.
In summary, the sources argue that the "true purpose of modeling" is to provide an informed framework for decision-making under uncertainty
. As noted in the transcripts, the fact that models are "imperfect" and cannot "predict" the future is exactly why the work of a quant—building, testing, and updating estimates—remains essential

quantifying a statistical edge
Expected Value (EV): This tells us, on average, how much net P&L can be estimated per trade over the long run
.
Even if a model only has a 51% to 53% win rate (barely better than a coin flip), if it has a positive EV and the researcher makes a "bulk" of small bets, the cumulative returns will grow smoothly over tim

The goal of quantitative modeling is consistently defined as estimating the likelihood of different states of the world rather than attempting to "predict" specific outcomes.

1. Generalizaciones como Rangos de Probabilidad
Las generalizaciones dejan de ser etiquetas estáticas para convertirse en estimaciones de comportamiento agregado. Útiles para describir la realidad cuando son pertinentes, estas generalizaciones permiten manejar un "volumen de resultados probables" ante variables independientes. No intentamos "predecir" qué hará un individuo, sino que estimamos cómo se comportará el sistema en su conjunto basándonos en patrones recurrentes.

2. Relativismo vs. Incerteza Estadística
El relativismo a menudo confunde la falta de una verdad absoluta con la falta de una estructura objetiva. Sin embargo, desde una óptica técnica, lo que existe no es una "verdad relativa", sino una incerteza inherente. La realidad objetiva se manifiesta no en un único evento que podemos "predecir", sino en la consistencia de las leyes que permiten estimar resultados. La subjetividad es solo el ruido en la medición de un fenómeno que sigue siendo independiente de nosotros.

3. Evidencias: La Consistencia del Azar
La evidencia de una realidad objetiva no reside en la capacidad de "predecir" el futuro (lo cual resulta ilógico ante variables aleatorias), sino en la estabilidad de las distribuciones. El hecho de que podamos estimar con precisión el margen de error y la dispersión de un fenómeno es la prueba de que existe una mecánica subyacente. La realidad objetiva es el motor que genera ese "bulk of probable outcomes".

4. Fenómenos: Mecánica sin Narrativa
La vida y sus eventos no son cuestión de apreciación artística, sino de procesos estocásticos. Considerar que se puede "predecir" un evento es, en muchos sentidos, una forma de narrativa humana (un intento de imponer orden al caos). Por el contrario, la estimación de eventos independientes trata al fenómeno como lo que es: una transición de estado en un sistema físico o biológico. El evento ocurre por causalidad mecánica, y nuestra capacidad de análisis se limita a calcular la probabilidad de su ocurrencia dentro de un espectro de posibilidades.

## README: Monte Carlo Simulation for Stock Price Estimation

### Project Overview
This project demonstrates the use of Monte Carlo simulations to estimate potential future stock prices for a given ticker symbol. The core idea is not to 'predict' a single future price, but rather to simulate a wide range of possible price paths based on historical volatility and returns, providing a distribution of probable outcomes.

### Methodology
1.  **Data Acquisition**: Stock historical data (Open, High, Low, Close, Volume) is downloaded using the `yfinance` library for a specified ticker (e.g., 'PLTR').
2.  **Return Calculation**: Daily percentage returns are calculated from the 'Close' prices.
3.  **Monte Carlo Simulation Setup**:
    *   `num_simulations`: The number of individual price paths to simulate (e.g., 10,000).
    *   `num_days`: The time horizon for the simulation in trading days (e.g., 252 days, approximately one trading year).
    *   `last_price`: The most recent closing price of the stock.
    *   `mu` (mean return) and `sigma` (standard deviation of returns) are calculated from the historical daily returns.
4.  **Simulation Process**: For each simulation, a price path is generated over `num_days` using a geometric Brownian motion model. This model assumes that daily price changes are log-normally distributed, incorporating the historical mean return and volatility.
5.  **Result Analysis**: The final prices from all simulations are analyzed to find the median and identify the most likely price path.
6.  **Visualization**: The simulated price paths are plotted to visually represent the range of potential future prices.

### Key Concepts
*   **Monte Carlo Simulation**: A computational algorithm that relies on repeated random sampling to obtain numerical results. It's particularly useful for modeling phenomena with significant uncertainty.
*   **Geometric Brownian Motion**: A continuous-time stochastic process often used to model financial markets, particularly stock prices.
*   **Estimation vs. Prediction**: The project emphasizes that these simulations provide estimations of probable outcomes rather than deterministic predictions, aligning with the inherent uncertainty of financial markets.

### Libraries Used
*   `pandas`: For data manipulation and analysis.
*   `numpy`: For numerical operations, especially in simulations.
*   `matplotlib`: For plotting and visualization.
*   `yfinance`: For downloading historical stock data.
*   `scipy.stats.norm`: For normal distribution functions used in generating random price movements.

### How to Use
1.  Run the cells sequentially.
2.  Modify the `ticker` symbol in the data acquisition step to analyze different stocks.
3.  Adjust `num_simulations` and `num_days` to explore different simulation parameters.
"""

!pip install pandas numpy matplotlib yfinance

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import yfinance as yf
from scipy.stats import norm
import seaborn as sns
import warnings

# Configuración de seguridad: Evitar que warnings revelen rutas locales
warnings.filterwarnings('ignore', category=FutureWarning)
# Filtro general para limpiar la salida de paths del sistema
def warning_cleaner(message, category, filename, lineno, file=None, line=None):
    print(f"{category.__name__}: {message}")

warnings.showwarning = warning_cleaner

"""# Un Ticker"""

df = yf.download("AAPL", start='1950-01-01', group_by='ticker', auto_adjust=True)

## df = df.sort_index(ascending=True)
df.head(1)

df["Returns"]=df[('AAPL', 'Close')].pct_change()
df.head(3)

num_simulations=10000
num_days=252 #predict horizon
last_price=df[('AAPL', 'Close')].iloc[-1]

simulation_df=np.zeros((num_days,num_simulations))

mu=df["Returns"].mean()
sigma=df["Returns"].std()

for i in range(num_simulations):
  price_list=[last_price]
  for j in range(num_days):
    price=price_list[-1] * np.exp((mu - 0.5 * sigma**2) + sigma * np.random.normal())
    price_list.append(price)
  simulation_df[:,i]=price_list[1:]

final_prices=simulation_df[-1,:]
median_final_prices=np.median(final_prices)

most_likely_price_index=np.argmin(np.abs(final_prices-median_final_prices))
most_likely_price_simulation=simulation_df[:,most_likely_price_index]

plt.figure(figsize=(10,7))
plt.plot(simulation_df)
plt.title("Monte Carlo Simulation")
plt.xlabel("Days")
plt.ylabel("Price")
plt.show()

print(f"The most likely PLTR simulation final price is: {most_likely_price_simulation[-1]}")

print(f"Todays PLTR price is: {df.tail(1)}")

"""# Varios Tickers"""

mis_tickers = ["AAPL",
               "MSFT",
               "GOOGL",
               "AMZN",
               "META",
               "PLTR"]

mis_tickers = ["AAPL", "MSFT", "GOOGL", "AMZN", "META", "PLTR"]
df2 = yf.download(mis_tickers, start='1950-01-01', group_by='ticker', auto_adjust=True)

for ticker in mis_tickers:
    df2[(ticker, 'Returns')] = df2[(ticker, 'Close')].pct_change()

num_simulations=10000
num_days=22 #predict horizon

for ticker in mis_tickers:
  last_price=df2[(ticker, 'Close')].iloc[-1]


simulation_df=np.zeros((num_days,num_simulations))

# Correctly access all 'Returns' columns from the MultiIndex
returns_data = df2.xs('Returns', level=1, axis=1)
mu = returns_data.mean().mean() # Mean of all ticker returns
sigma = returns_data.std().mean() # Average std deviation across tickers

# Dictionaries to store results for each ticker
all_ticker_simulation_dfs = {}
all_ticker_most_likely_prices = {}
all_ticker_median_final_prices = {}

for current_ticker in mis_tickers:
    print(f"--- Simulating for {current_ticker} ---")

    # Get ticker-specific parameters
    last_price = df2[(current_ticker, 'Close')].iloc[-1]

    # Calculate mu and sigma for the current ticker
    ticker_returns = df2[(current_ticker, 'Returns')].dropna() # Drop NaN for calculation
    mu = ticker_returns.mean()
    sigma = ticker_returns.std()

    # Initialize simulation_df for the current ticker
    simulation_df = np.zeros((num_days, num_simulations))

    # Run Monte Carlo simulation
    for i in range(num_simulations):
        price_list = [last_price]
        for j in range(num_days):
            price = price_list[-1] * np.exp((mu - 0.5 * sigma**2) + sigma * np.random.normal())
            price_list.append(price)
        simulation_df[:, i] = price_list[1:]

    # Analyze results
    final_prices = simulation_df[-1, :]
    median_final_prices = np.median(final_prices)
    most_likely_price_index = np.argmin(np.abs(final_prices - median_final_prices))
    most_likely_price_simulation = simulation_df[:, most_likely_price_index]

    # Store results
    all_ticker_simulation_dfs[current_ticker] = simulation_df
    all_ticker_most_likely_prices[current_ticker] = most_likely_price_simulation[-1]
    all_ticker_median_final_prices[current_ticker] = median_final_prices

    # Plotting for the current ticker
    plt.figure(figsize=(10, 7))
    plt.plot(simulation_df)
    plt.plot(most_likely_price_simulation, color='red', linestyle='--', label=f'Most Likely Path ({current_ticker})')
    plt.title(f"Monte Carlo Simulation for {current_ticker}")
    plt.xlabel("Days")
    plt.ylabel("Price")
    plt.legend()
    plt.show()

    # Print results for the current ticker
    print(f"The most likely {current_ticker} simulation final price is: {all_ticker_most_likely_prices[current_ticker]:.2f}")
    print(f"The median {current_ticker} simulation final price is: {all_ticker_median_final_prices[current_ticker]:.2f}")
    print("-" * 50)

# Consolidated summary of results for all tickers
print(f"\n--- Consolidated Analysis for All Tickers (Prediction Horizon: {num_days} days, Simulations: {num_simulations}) ---")
for ticker in mis_tickers:
    simulated_price = all_ticker_most_likely_prices[ticker]
    current_price = df2[(ticker, 'Close')].iloc[-1]
    print(f"{ticker}: Most Likely Simulated Final Price: {simulated_price:.3f} | Today's Current Price: {current_price:.3f}")

"""## Distribución de Precios Finales Simulados"""

for ticker in mis_tickers:
    plt.figure(figsize=(10, 6))
    final_prices = all_ticker_simulation_dfs[ticker][-1, :]
    sns.histplot(final_prices, bins=50, kde=True, color='skyblue')
    plt.title(f'Distribución de Precios Finales Simulados para {ticker}')
    plt.xlabel('Precio Final')
    plt.ylabel('Frecuencia')
    plt.axvline(all_ticker_median_final_prices[ticker], color='red', linestyle='--', label=f'Mediana: {all_ticker_median_final_prices[ticker]:.2f}')
    plt.axvline(df2[(ticker, 'Close')].iloc[-1], color='green', linestyle=':', label=f'Precio Actual: {df2[(ticker, 'Close')].iloc[-1]:.2f}')
    plt.legend()
    plt.grid(True, alpha=0.7)
    plt.show()

"""## Intervalo de Confianza del 95% para los Precios Finales Simulados"""

print("--- 95% Confidence Interval for Simulated Final Prices ---")
for ticker in mis_tickers:
    final_prices = all_ticker_simulation_dfs[ticker][-1, :]
    lower_bound = np.percentile(final_prices, 2.5)
    upper_bound = np.percentile(final_prices, 97.5)
    print(f"{ticker}: 95% CI: [{lower_bound:.3f}, {upper_bound:.3f}]")

plt.figure(figsize=(12, 7))

confidence_data = []
for ticker in mis_tickers:
    final_prices = all_ticker_simulation_dfs[ticker][-1, :]
    lower_bound = np.percentile(final_prices, 2.5)
    upper_bound = np.percentile(final_prices, 97.5)
    median_price = all_ticker_median_final_prices[ticker]
    current_price = df2[(ticker, 'Close')].iloc[-1]
    confidence_data.append({
        'Ticker': ticker,
        'Lower Bound': lower_bound,
        'Upper Bound': upper_bound,
        'Median Price': median_price,
        'Current Price': current_price
    })

confidence_df = pd.DataFrame(confidence_data)

# Updated: Using linestyle='none' instead of deprecated join=False
sns.pointplot(x='Ticker', y='Median Price', data=confidence_df, linestyle='none', color='red', markers='o', capsize=0.2, label='Median Simulated Price')
plt.errorbar(x=confidence_df['Ticker'], y=confidence_df['Median Price'], yerr=[confidence_df['Median Price'] - confidence_df['Lower Bound'], confidence_df['Upper Bound'] - confidence_df['Median Price']], fmt='none', capsize=5, color='gray', linewidth=2, label='95% Confidence Interval')

# Add current prices as separate points
sns.scatterplot(x='Ticker', y='Current Price', data=confidence_df, color='blue', marker='X', s=200, label='Current Price')

plt.title('Intervalos de Confianza del 95% para Precios Finales Simulados')
plt.xlabel('Ticker')
plt.ylabel('Precio')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

"""### Insight Rápido de la Visualización del Intervalo de Confianza

Este gráfico nos permite visualizar rápidamente la **dispersión y el rango probable de precios futuros** para cada acción, basándose en la simulación de Monte Carlo. Cada línea gris vertical representa el intervalo de confianza del 95%, lo que significa que el 95% de nuestras simulaciones terminaron dentro de ese rango de precios.

*   **Puntos Rojos (Median Simulated Price)**: Indican el precio mediano estimado por la simulación para cada ticker. Este es el resultado más probable o central de todas las simulaciones.
*   **Puntos Azules (Current Price)**: Muestran el precio actual de cada acción. Esto nos permite comparar la estimación simulada con el punto de partida real.

**Observaciones clave:**

1.  **Potencial de crecimiento/caída**: Si el punto azul (precio actual) está por debajo de la parte inferior del intervalo de confianza o muy por debajo del precio mediano, podría sugerir un posible **potencial alcista** según el modelo. Por el contrario, si el precio actual está cerca o por encima del límite superior del CI, podría indicar un **riesgo de caída** o que el precio ya está en la parte alta de la distribución probable.
2.  **Volatilidad implicada**: La longitud de la barra gris (el intervalo de confianza) es una representación visual de la **volatilidad esperada** para cada acción. Un intervalo más amplio sugiere una mayor incertidumbre o una mayor dispersión de posibles precios futuros.

En resumen, el gráfico facilita la comparación entre el precio actual de una acción y el rango de precios que el modelo de Monte Carlo estima como más probable para el futuro, ofreciendo una perspectiva sobre el posible riesgo y recompensa.
"""